server:
  port: 8082
  
camel:
  springboot:
    name: ServicesRest_BizarreGate
    
management:
  port: 8081
  
endpoints:
  enabled: false
  health:
    enabled: true
    
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

bizarre:
  api:
    path: '/bizarre/gate'
    serverPort: '8082'