server:
  port: 8083
  
camel:
  springboot:
    name: ServicesRest_BizarreHypixel
    
management:
  port: 8081
  
endpoints:
  enabled: false
  health:
    enabled: true
    
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

bizarre:
  api:
    path: '/bizarre/hypixel'
    serverPort: '8083'