server:
  port: 8085
  
camel:
  springboot:
    name: ServicesRest_BizarreSql
    
management:
  port: 8081
  
endpoints:
  enabled: false
  health:
    enabled: true
    
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

bizarre:
  api:
    path: '/bizarre/sql'
    serverPort: '8085'